config/routes.rb
Rails.application.routes.draw do
  get 'api/public' => 'public#public'
  get 'api/private' => 'private#private'
  get 'api/private-scoped' => 'private#private_scoped'
  
  root 'procedures#index'
  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/auth/logout' => 'auth0#logout'
  get '/auth/redirect' => 'auth0#redirect'
  get '/' => redirect('/procedures') #'#procedures'
      resources :procedures do
        resources :comments
        resources :temperatures
      end
end

app/models/temperature.rb
class Temperature < ApplicationRecord
  belongs_to :procedure
  broadcasts_to :procedure
  after_create_commit -> { broadcast_append_to :procedure }
  after_destroy_commit -> { broadcast_remove_to :procedure }
  after_update_commit -> { broadcast_replace_to :procedure }
end

app/controllers/temperatures_controller.rb
class TemperaturesController < ApplicationController
    before_action :set_procedure
    before_action :set_temperature, only: %i[ edit update destroy ]
  
    def new
      @temperature = @procedure.temperatures.new
    end
    
      # GET /procedures/1/edit
    def edit
    end
  
    def create
      @temperature = @procedure.temperatures.create!(temperature_params)
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to @procedure }
      end
    end

       # PATCH/PUT /tickets/1 or /tickets/1.json
  def update
    respond_to do |format|
      if @temperature.update(temperature_params)
        format.turbo_stream
        format.html { redirect_to @temperature, notice: "temperature was successfully updated." }
        format.json { render :show, status: :ok, location: @temperature }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @temperature.errors, status: :unprocessable_entity }
      end
    end
  end
  
    private
  
    def set_procedure
      @procedure = Procedure.find(params[:procedure_id])
    end
  
    def set_temperature
      @temperature = @procedure.temperatures.find(params[:id])
    end
  
    def temperature_params
      params.require(:temperature).permit(:title)
    end
  
end

app/views/temperatures/_temperature.html.erb
<div>
    
    <%= turbo_frame_tag dom_id(temperature) do %>
        <div class="">
              <%= temperature.title %>
              <!-- <%= range_field_tag 'title', temperature.title, :in => 0..100, :step => '.1' %> -->
              <div class="progress">
                <div class="determinate" style="width: <%= temperature.title %>%"></div>
            </div>
        </div>
    <% end %>
    <% if @procedure.present? %>
        <%= turbo_frame_tag dom_id(temperature), src: edit_procedure_temperature_path(@procedure, temperature), target: :_top %>
    <% end %>
    <% if @procedure.present? %>
        <%= link_to 'Go To Edit View', edit_procedure_temperature_path(@procedure, temperature), class: 'btn m-l-5' %>
    <% end %>
</div>

app/views/temperatures/create.turbo_stream.erb
<%# turbo_stream.append 'temperatures', @temperature %>

app/views/temperatures/edit.html.erb
<%= turbo_frame_tag dom_id(@temperature) do %>
    <h6>Update temperature</h6>
    <% if @procedure.present? %>
      <%= form_with model: [@procedure, @temperature],
          data: { controller: 'edit-temperature', action: 'turbo:submit-end->edit-temperature#reset' } do |form| %>
          <div class='field'>
            <p class="range-field">
              <%= form.range_field :title, :in => 0..100, :step => '.1' %>
            </p>
          <%= form.submit :'data-edit-temperature-target' => 'button', :class => 'btn m-t-10 m-b-10' %>
          </div>
            </form>
      <% end %>
    <% end %>
    <%= link_to 'Go to Procedures', procedures_path, 'data-turbo-frame': :_top, :class => 'btn' %>
  <% end %>

app/views/temperatures/new.html.erb
<%= turbo_frame_tag 'new_temperature' do %>
  <span class="card-title">New temperature</span>
  <%= form_with model: [@procedure, @temperature],
        data: { controller: 'reset-form', action: 'turbo:submit-end->reset-form#reset' } do |form| %>
          <div class='field'>
            <%= form.range_field :title, :in => 0..100, :step => '.1' %>
            <%= form.submit :class => 'btn', 'data-reset-form-target': 'button' %>
          </div>
  <% end %>
<% end %>