config/routes.rb
Rails.application.routes.draw do
  get 'api/public' => 'public#public'
  get 'api/private' => 'private#private'
  get 'api/private-scoped' => 'private#private_scoped'
  
  root 'procedures#index'
  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/auth/logout' => 'auth0#logout'
  get '/auth/redirect' => 'auth0#redirect'
  get '/' => redirect('/procedures') #'#procedures'
      resources :procedures do
        resources :comments
        resources :temperatures
      end
end

app/models/procedure.rb
class Procedure < ApplicationRecord
    has_rich_text :content
    has_many :comments, dependent: :destroy
    has_many :temperatures, dependent: :destroy

    broadcasts
    after_create_commit -> { broadcast_append_to self }
    after_destroy_commit -> { broadcast_remove_to self }
    after_update_commit -> { broadcast_replace_to self }
end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
  # include Secured
  # before_action :set_user
  before_action :set_procedure, only: %i[ show edit update destroy ]
  
  # GET /procedures or /procedures.json
  def index
    @procedures = Procedure.all
  end

  # GET /procedures/1 or /procedures/1.json
  def show
  end

  # GET /procedures/new
  def new
    @procedure = Procedure.new
  end

  # GET /procedures/1/edit
  def edit
  end

  # POST /procedures or /procedures.json
  def create
    @procedure = Procedure.new(procedure_params)

    respond_to do |format|
      if @procedure.save
        format.turbo_stream
        format.html { redirect_to @procedure, notice: "Procedure was successfully created." }
        format.json { render :show, status: :created, location: @procedure }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @procedure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /procedures/1 or /procedures/1.json
  def update
    respond_to do |format|
      if @procedure.update(procedure_params)
        format.html { redirect_to @procedure, notice: "Procedure was successfully updated." }
        format.json { render :show, status: :ok, location: @procedure }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @procedure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /procedures/1 or /procedures/1.json
  def destroy
    @procedure.destroy
    respond_to do |format|
      format.html { redirect_to procedures_url, notice: "Procedure was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_procedure
      @procedure = Procedure.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def procedure_params
      params.require(:procedure).permit(:title, :content)
    end

    def set_user
      @user = session[:userinfo]
    end
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/views/procedures/_form.html.erb
<%= form_with(model: procedure) do |form| %>

<div class="col s12 m12">
  <div class="card grey darken-3">
      <div class="card-content ">
        <% if procedure.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(procedure.errors.count, "error") %> prohibited this procedure from being saved:</h2>
    
          <ul>
            <% procedure.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    
      <div class="field">
        <%= form.label :title, class: '' %>
        <%= form.text_field :title, class: '' %>
        <%= form.label :content, class: '' %>
        <%= form.rich_text_area :content, class: '' %>
      </div>
      </div>
      <div class="card-action black-text"><%= form.submit :class => 'btn m-t-10 m-b-10' %></div>
  </div>
</div>
<% end %>

app/views/procedures/_procedure.html.erb
<div class="col s12 m12">
  <div class="card grey darken-3">
    <div class="card-content">
      <span class="card-title">Procedure<i class="material-icons right">close</i></span>
      <%= time_ago_in_words(procedure.created_at) %> ago
      <%= turbo_frame_tag :div, id: dom_id(procedure) do %>
        <h5><%= procedure.title %></h5>
        <p><%= procedure.content %></p>
      <% end %>
    </div>
    <div class="card-action">
      <%= link_to 'Edit', edit_procedure_path(@procedure) %>
      <%= link_to 'Back', procedures_path, 'data-turbo-frame': :_top %>
    </div>
  </div>
</div>

app/views/procedures/create.turbo_stream.erb
<%# turbo_stream.append 'procedures', @procedure %>

app/views/procedures/edit.html.erb
<h6>Editing Procedure</h6>

<%= render 'form', procedure: @procedure %>

<%= link_to 'Show', @procedure %> |
<%= link_to 'Back', procedures_path %>

app/views/procedures/index.html.erb
<p id="notice"><%= notice %></p>
<h5>Procedures</h5>
<%= button_to 'Login', 'auth/auth0', method: :post, class: 'btn btn-success btn-lg', id: 'qsLoginBtn' unless session[:userinfo].present? %>
<%= link_to 'Back', procedures_path, 'data-turbo-frame': :_top %>
<!-- <div class="panel panel-default">
    <div class="panel-heading">Normalized User Profile</div>
    <div class="panel-body">
      <pre><%= JSON.pretty_generate(@user) %></pre>
      <pre><% unless @user.blank? %><%= @user.as_json %><% end %></pre>
    </div>
</div> -->
<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Created On</th>
            <th class="right">Action</th>
        </tr>
    </thead>

    <tbody>
        <% @procedures.each do |procedure| %>
        <tr>
            <td><%= procedure.title %></td>
            <%= link_to procedure, class: "p-0" do %> View <% end %>
            <td><%= time_tag procedure.created_at, datetime: procedure.created_at.strftime('%G-W%V') %></td>
            <td>
                <%= link_to procedure, class: "p-0" do %> View <% end %>
                <a class="dropdown-trigger right" href="#" data-target="procedure-actions"><i class="material-icons">more_vert</i></a>
                <ul id="procedure-actions" class="dropdown-content">
                    <li class="flex flex-row vertical-center m-r-10">
                        <i class="p-l-10 material-icons">visibility</i>
                        <%= link_to procedure, class: "p-0" do %> View <% end %>
                    </li>
                    <li class="flex flex-row vertical-center p-r-2">
                        <i class="p-l-10 material-icons">edit</i>
                        <%= link_to edit_procedure_path(procedure), class: "" do %> Edit <% end %>
                    </li>
                    <li class="divider" tabindex="-1"></li>
                    <li><%= link_to 'Destroy', procedure, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                </ul>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>
<!-- <script>
    var settings = {
"async": true,
"url": "https://atulub.us.auth0.com/oauth/token",
"method": "POST",
"headers": {
  "content-type": "application/json",
},
"data": "{\"client_id\":\"P1ExlWvgX59OJzdCVcyfQbbxZEFZYK2H\",\"client_secret\":\"BPaqu1OS_ATxzTZ82LVDvRoVa7uI1HDeglgnbmHporKfat_yfVHj0f4ZRXhaRJ2T\",\"audience\":\"https://atulub.us.auth0.com/api/v2/\",\"grant_type\":\"client_credentials\"}"
}

$.ajax(settings).done(function (response) {
console.log(response);
});
  </script> -->
<br />
<%= link_to 'New Procedure', new_procedure_path, class: 'btn' %>

app/views/procedures/new.html.erb
<h5>New Procedure</h5>

<%= render 'form', procedure: @procedure %>

<%= link_to 'Back', procedures_path %>

app/views/procedures/show.html.erb
<div class="row">
    <p id="notice"><%= notice %></p>
    <%= turbo_stream_from @procedure %> <%= render @procedure %>
    <div class="col s12 m12">
        <ul class="collapsible grey darken-3">
            <li>
                <div class="collapsible-header grey darken-3"><i class="material-icons">comments</i>Comments</div>
                <div class="collapsible-body">
                    <div class="card-content">
                        <span class="card-title">Comments</span>
                        <div id="comments"><%= render @procedure.comments %></div>
                        <%= turbo_frame_tag 'new_comment', src: new_procedure_comment_path(@procedure), target: :_top %>
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="col s12 m12">
        <div class="card grey darken-3">
            <div class="card-content">
                <span class="card-title">Temperature</span>
                <div id="temperatures"><%= render @procedure.temperatures, procedure: @procedure %></div>
                <% if @procedure.temperatures.blank? %>
                    <%= turbo_frame_tag 'new_temperature', src: new_procedure_temperature_path(@procedure), target: :_top %>
                <% end %>
            </div>
        </div>
    </div>
</div>

<!-- 
<%= turbo_frame_tag 'custom-button-controller' do %>
  <div data-controller="custom-button">
    <button data-custom-button-target="button" data-action="click->custom-button#reset">
      Greet
    </button>
    <span data-custom-button-target="output">
    </span>
  </div>
<% end %> -->